version: '3'

services:
  dev:
    image: node:20 
    working_dir: /website
    entrypoint: npm run dev -- --host
    volumes:
      - ../website:/website:rw
    ports:
      - "5173:5173"
  install-dependencies:
    image: node:20 
    working_dir: /website
    entrypoint: npm i
    volumes:
      - ../website:/website:rw
  bash:
    image: node:20 
    working_dir: /project
    entrypoint: bash
    volumes:
      - ..:/project:rw